require 'date'
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Source.create(type: "Rulebook", name: "Core Rulebook", release_date: Date.new(2019,8,1))
Source.create(type: "Rulebook", name: "Bestiary", release_date: Date.new(2019,8,1))
Source.create(type: "Rulebook", name: "Gamemastery Guide", release_date: Date.new(2020,2,26))
Source.create(type: "Rulebook", name: "Bestiary 2", release_date: Date.new(2020,5,27))
Source.create(type: "Rulebook", name: "Advanced Player's Guide", release_date: Date.new(2020,7,30))
Source.create(type: "Rulebook", name: "Pathfinder Beginner Box: Game Master's Guide", release_date: Date.new(2020,10,15))
Source.create(type: "Rulebook", name: "Pathfinder Beginner Box: Hero's Handbook", release_date: Date.new(2020,10,15))
Source.create(type: "Rulebook", name: "Bestiary 3", release_date: Date.new(2021,4,7))
Source.create(type: "Rulebook", name: "Secrets of Magic", release_date: Date.new(2021,9,1))
Source.create(type: "Rulebook", name: "Guns & Gears", release_date: Date.new(2021,10,13))
Source.create(type: "Rulebook", name: "Book of the Dead", release_date: Date.new(2022,4,27))

Trait.create(name: "Chaotic", type: "Alignment")
Trait.create(name: "Lawful", type: "Alignment")
Trait.create(name: "Evil", type: "Alignment")
Trait.create(name: "Good", type: "Alignment")
Trait.create(name: "Aasimar", type: "Ancestry")
Trait.create(name: "Anadi", type: "Ancestry")
Trait.create(name: "Android", type: "Ancestry")
Trait.create(name: "Aphorite", type: "Ancestry")
Trait.create(name: "Automaton", type: "Ancestry")
Trait.create(name: "Azarketi", type: "Ancestry")
Trait.create(name: "Beastkin", type: "Ancestry")
Trait.create(name: "Catfolk", type: "Ancestry")
Trait.create(name: "Changling", type: "Ancestry")
Trait.create(name: "Conrasu", type: "Ancestry")
Trait.create(name: "Dhampir", type: "Ancestry")
Trait.create(name: "Duskwalker", type: "Ancestry")
Trait.create(name: "Dwarf", type: "Ancestry")
Trait.create(name: "Elf", type: "Ancestry")
Trait.create(name: "Fetchling", type: "Ancestry")
Trait.create(name: "Fleshwarp", type: "Ancestry")
Trait.create(name: "Ganzi", type: "Ancestry")
Trait.create(name: "Geniekin", type: "Ancestry")
Trait.create(name: "Gnoll", type: "Ancestry")
Trait.create(name: "Gnome", type: "Ancestry")
Trait.create(name: "Goblin", type: "Ancestry")
Trait.create(name: "Goloma", type: "Ancestry")
Trait.create(name: "Grippli", type: "Ancestry")
Trait.create(name: "Half-Elf", type: "Ancestry")
Trait.create(name: "Halfling", type: "Ancestry")
Trait.create(name: "Half-Orc", type: "Ancestry")
Trait.create(name: "Hobgoblin", type: "Ancestry")
Trait.create(name: "Human", type: "Ancestry")
Trait.create(name: "Ifrit", type: "Ancestry")
Trait.create(name: "Kitsune", type: "Ancestry")
Trait.create(name: "Kobold", type: "Ancestry")
Trait.create(name: "Leshy", type: "Ancestry")
Trait.create(name: "Lizardfolk", type: "Ancestry")
Trait.create(name: "Orc", type: "Ancestry")
Trait.create(name: "Oread", type: "Ancestry")
Trait.create(name: "Poppet", type: "Ancestry")
Trait.create(name: "Ratfolk", type: "Ancestry")
Trait.create(name: "Shisk", type: "Ancestry")
Trait.create(name: "Shoony", type: "Ancestry")
Trait.create(name: "Skeleton", type: "Ancestry")
Trait.create(name: "Sprite", type: "Ancestry")
Trait.create(name: "Strix", type: "Ancestry")
Trait.create(name: "Suli", type: "Ancestry")
Trait.create(name: "Sylph", type: "Ancestry")
Trait.create(name: "Tengu", type: "Ancestry")
Trait.create(name: "Tiefling", type: "Ancestry")
Trait.create(name: "Undine", type: "Ancestry")

Trait.create(name: "Bulwark", type: "Armor")
Trait.create(name: "Comfort", type: "Armor")
Trait.create(name: "Flexible", type: "Armor")
Trait.create(name: "Noisy", type: "Armor")

Trait.create(name: "Alchemist", type: "Class")
Trait.create(name: "Barbarian", type: "Class")
Trait.create(name: "Bard", type: "Class")
Trait.create(name: "Champion", type: "Class")
Trait.create(name: "Cleric", type: "Class")
Trait.create(name: "Druid", type: "Class")
Trait.create(name: "Fighter", type: "Class")
Trait.create(name: "Gunslinger", type: "Class")
Trait.create(name: "Inventor", type: "Class")
Trait.create(name: "Investigator", type: "Class")
Trait.create(name: "Magus", type: "Class")
Trait.create(name: "Monk", type: "Class")
Trait.create(name: "Oracle", type: "Class")
Trait.create(name: "Ranger", type: "Class")
Trait.create(name: "Rogue", type: "Class")
Trait.create(name: "Sorcerer", type: "Class")
Trait.create(name: "Summoner", type: "Class")
Trait.create(name: "Swashbuckler", type: "Class")
Trait.create(name: "Witch", type: "Class")
Trait.create(name: "Wizard", type: "Class")

Trait.create(name: "Addititve", type: "Class-Specific")
Trait.create(name: "Composition", type: "Class-Specific")
Trait.create(name: "Cursebound", type: "Class-Specific")
Trait.create(name: "Eidolon", type: "Class-Specific")
Trait.create(name: "Evolution", type: "Class-Specific")
Trait.create(name: "Finisher", type: "Class-Specific")
Trait.create(name: "Hex", type: "Class-Specific")
Trait.create(name: "Infused", type: "Class-Specific")
Trait.create(name: "Instinct", type: "Class-Specific")
Trait.create(name: "Litany", type: "Class-Specific")
Trait.create(name: "Modification", type: "Class-Specific")
Trait.create(name: "Oath", type: "Class-Specific")
Trait.create(name: "Rage", type: "Class-Specific")
Trait.create(name: "Social", type: "Class-Specific")
Trait.create(name: "Stance", type: "Class-Specific")
Trait.create(name: "Tandem", type: "Class-Specific")
Trait.create(name: "Unstable", type: "Class-Specific")
Trait.create(name: "Vigilante", type: "Class-Specific")

Trait.create(name: "Aberration", type: "Creature Type")
Trait.create(name: "Animal", type: "Creature Type")
Trait.create(name: "Astral", type: "Creature Type")
Trait.create(name: "Beast", type: "Creature Type")
Trait.create(name: "Celestial", type: "Creature Type")
Trait.create(name: "Construct", type: "Creature Type")
Trait.create(name: "Dragon", type: "Creature Type")
Trait.create(name: "Dream", type: "Creature Type")
Trait.create(name: "Elemental", type: "Creature Type")
Trait.create(name: "Ethereal", type: "Creature Type")
Trait.create(name: "Fey", type: "Creature Type")
Trait.create(name: "Fiend", type: "Creature Type")
Trait.create(name: "Fungus", type: "Creature Type")
Trait.create(name: "Giant", type: "Creature Type")
Trait.create(name: "Humanoid", type: "Creature Type")
Trait.create(name: "Monitor", type: "Creature Type")
Trait.create(name: "Negative", type: "Creature Type")
Trait.create(name: "Ooze", type: "Creature Type")
Trait.create(name: "Petitioner", type: "Creature Type")
Trait.create(name: "Plant", type: "Creature Type")
Trait.create(name: "Positive", type: "Creature Type")
Trait.create(name: "Spirit", type: "Creature Type")
Trait.create(name: "Time", type: "Creature Type")
Trait.create(name: "Undead", type: "Creature Type")

Trait.create(name: "Air", type: "Elemental")
Trait.create(name: "Earth", type: "Elemental")
Trait.create(name: "Fire", type: "Elemental")
Trait.create(name: "Water", type: "Elemental")

Trait.create(name: "Acid", type: "Energy")
Trait.create(name: "Cold", type: "Energy")
Trait.create(name: "Electricity", type: "Energy")
Trait.create(name: "Fire", type: "Energy")
Trait.create(name: "Force", type: "Energy")
Trait.create(name: "Negative", type: "Energy")
Trait.create(name: "Positive", type: "Energy")
Trait.create(name: "Sonic", type: "Energy")

Trait.create(name: "Adjustment", type: "Equipment")
Trait.create(name: "Alchemical", type: "Equipment")
Trait.create(name: "Apex", type: "Equipment")
Trait.create(name: "Artifact", type: "Equipment")
Trait.create(name: "Bomb", type: "Equipment")
Trait.create(name: "Catalyst", type: "Equipment")
Trait.create(name: "Clockwork", type: "Equipment")
Trait.create(name: "Companion", type: "Equipment")
Trait.create(name: "Consumable", type: "Equipment")
Trait.create(name: "Contract", type: "Equipment")
Trait.create(name: "Cursed", type: "Equipment")
Trait.create(name: "Drug", type: "Equipment")
Trait.create(name: "Elixer", type: "Equipment")
Trait.create(name: "Focused", type: "Equipment")
Trait.create(name: "Fulu", type: "Equipment")
Trait.create(name: "Gadget", type: "Equipment")
Trait.create(name: "Grimoire", type: "Equipment")
Trait.create(name: "Intelligent", type: "Equipment")
Trait.create(name: "Invested", type: "Equipment")
Trait.create(name: "Mechanical", type: "Equipment")
Trait.create(name: "Mutagen", type: "Equipment")
Trait.create(name: "Oil", type: "Equipment")
Trait.create(name: "Potion", type: "Equipment")
Trait.create(name: "Saggorak", type: "Equipment")
Trait.create(name: "Scroll", type: "Equipment")
Trait.create(name: "Snare", type: "Equipment")
Trait.create(name: "Spellheart", type: "Equipment")
Trait.create(name: "Staff", type: "Equipment")
Trait.create(name: "Steam", type: "Equipment")
Trait.create(name: "Structure", type: "Equipment")
Trait.create(name: "Talisman", type: "Equipment")
Trait.create(name: "Tattoo", type: "Equipment")
Trait.create(name: "Trap", type: "Equipment")
Trait.create(name: "Wand", type: "Equipment")

Trait.create(name: "Environmental", type: "Hazard")
Trait.create(name: "Haunt", type: "Hazard")
Trait.create(name: "Mechanical", type: "Hazard")
Trait.create(name: "Trap", type: "Hazard")

Trait.create(name: "Aasimar", type: "Monster")
Trait.create(name: "Acid", type: "Monster")
Trait.create(name: "Aeon", type: "Monster")
Trait.create(name: "Aesir", type: "Monster")
Trait.create(name: "Agathion", type: "Monster")
Trait.create(name: "Air", type: "Monster")
Trait.create(name: "Alchemical", type: "Monster")
Trait.create(name: "Amphibious", type: "Monster")
Trait.create(name: "Anadi", type: "Monster")
Trait.create(name: "Angel", type: "Monster")
Trait.create(name: "Anugobu", type: "Monster")
#not completed: Not all triats listed, type should be removed (it came from Nethys, not Paizo), duplicates exist

#Ancestries still require Ability Modifiers and Langauges for base, as well as additional specific stuff to each ancestry
dwarfAncestry = Ancestry.create(name: "Dwarf", hit_points: 10, size: "Medium", speed: 20, vision: "Darkvision")
elfAncestry = Ancestry.create(name: "Elf", hit_points: 6, size: "Medium", speed: 30, vision: "Low-Light")
gnomeAncestry = Ancestry.create(name: "Gnome", hit_points: 8, size: "Small", speed: 25, vision: "Low-Light")
goblinAncestry = Ancestry.create(name: "Goblin", hit_points: 6, size: "Small", speed: 25, vision: "Darkvision")
halflingAncestry = Ancestry.create(name: "Hafling", hit_points: 6, size: "Small", speed: 25, vision: nil)
humanAncestry = Ancestry.create(name: "Human", hit_points: 8, size: "Medium", speed: 25, vision: nil)

